#!/bin/bash
# run app
if [ $# -eq 1 ]; then
    HBNB_MYSQL_USER=hbnb_dev HBNB_MYSQL_PWD=hbnb_dev_pwd HBNB_MYSQL_HOST=localhost HBNB_MYSQL_DB=hbnb_dev_db HBNB_TYPE_STORAGE=db python3 -m web_dynamic."$1"
else
    echo "Usage: ./run-app <app name>"
fi
